<?php

// Les différents articles sous forme d'objet
$dataArticlesList = [
    1 => new Article(
        "Bernard l'hermite",
        "<p>Nous les franciliens, nous sommes comme des Bernard l'hermite. Sur notre gros rocher parisien, nous nous entassons comme des coquillages. Et lorsque nous déménageons, nous nous installons dans la coquille d'un autre, et prenons notre place. Nous ne nous déplaçons pas avec notre propre coquille, comme les gens du voyage avec leurs caravanes. Nous occupons une coquille vidée, qui a appartenu à quelqu'un d'autre, et que nous nous approprions, pour un temps, en attendant de la libérer pour le bernard l'hermite suivant.</p>
        <p>Quel étrange phénomène !</p>
        <p>Et pourtant si nous laissions à l'abandon chaque coquille sans se la réapproprier, nous aurions un cimetière de coquillages qui s'épendrait de plus en plus depuis l'épicentre. </p>
        <p>Alors d'une certaine manière, ce recyclage est écologique !</p>
        <p>Et alors lorsqu'on se glisse dans la peau d'un autre, est-ce qu'on en prend ses habitudes ? Est-ce qu'on se faufile un peu plus dans son quotidien, ses habitudes ? On répète les mêmes trajets, de la chambre à la cuisine, au salon. On passe la clef dans la même serrure, on regarde la même vue. Est-ce que la coquille finit par influencer le bernard ?</p>",
        1 // Id/index de la catégorie
    ),
    2 => new Article(
        "Défendre une cause",
        "<p>L'important n'est pas la cause défendue, mais la façon dont elle est défendue. Revendiquer quelque chose, dénoncer quelqu'un, s'élever contre un système ou défendre une idéologie... j'ai toujours eu un sentiment ambivalent vis à vis des personnes à conviction.</p>
        <p>D'un côté, je les admire, elles disent haut et fort ce qu'elles pensent, et de l'autre je trouve cela adolescent, réactionnaire et donc en lien avec ce contre quoi ils luttent, en ré-action et non pas en action libre et indépendante. En effet que se passera-t-il quand l'heure aura sonnée de la fin de ce contre quoi on lutte ? Serons-nous heureux ? Je ne le pense pas. Généralement c'est l'action de lutter, le sentiment jouissif d'être à contre courant et donc unique, que l'on recherche. C'est le processus qui nous fait plaisir et apporte une image flateuse de nous même, de rebelle, de précurseur. </p>
        <p>Alors quelle cause vaut le coût d'être défendue ? </p>
        <p>Finalement peu importe, ce n'est pas la cause qui compte mais le fait de s'élever, de se faire entendre, d'exister, de dominer. C'est la lutte qui est importante, gratifiante, la victoire si elle arrive ne dure qu'un temps très court, en attendant la prochaine lutte.</p>
        <p>C'est une façon d'exprimer sa rage, sa colère. </p>
        <p>S'indigner, c'est ne pas accepter une réalité. C'est le point de départ du vrai changement. Alors certes nous avons besoin de cela pour faire avancer les choses. Et en même temps je crois que les gens qui s'indignent d'une chose trouveront toujours un sujet pour continuer de s'indigner. Alors est-ce grâce à ces personnes que le monde bouge ? Sûrement, au passage. Mais je crois que l'état de rebellion est surtout une façon d'être et de vivre, un besoin pour ces personnes. L'origine ? Chacun doit avoir ses raisons, une thérapie sera mieux à même de les trouver que moi. </p>
        <p>Faut-il éteindre ce feu ? Je pense que certaines personnes peuvent accéder à l'acceptation, cette forme de sagesse. Et je pense que d'autres ne le peuvent pas ou tout simplement ne le veulent pas (ce serait disparaître, ne pas exister, car accepter est un peu se taire).</p>
        <p>Finalement la question est celle de la joie et du bonheur de l'individu : va-t-il être heureux dans la sagesse de l'acceptation, ou dans la force du combat ? Les deux semblent possibles. C'est donc une question de choix.</p>
        <p>Et finalement lorsque ce feu anime une personne, il peut là aussi y avoir un choix : faire entendre ses revendications dans la violence et la destruction, ou par l'art, la création.</p>
        <p>Dans ce dernier cas ce qui est intéressant c'est que la colère, le combat peuvent être source d'une vraie beauté, d'une vraie avancée, de quelque chose d'incroyable. Je ne sais pas si cela peut servir la cause, quoi que je pense que ça puisse bien mieux la servir que par les moyens de la destruction, mais surtout ça sert la cause de celui qui crée, qui trouve un terrain d'expression de son fort intérieur. Et en cela c'est déjà bénéfique. Mieux, il peut inspirer d'autres personnes. Mais je pense qu'il faut garder l'humilité de comprendre que tout ceci n'est pas fait de façon angélique et salutaire, pour le bien de tous, mais que cela part d'abord d'un sentiment personnel d'un individu, qui ensuite peut avoir des répercussions positives autour (et tant mieux). Cela contribue d'ailleurs à donner encore plus de joie à la personne créatrice. </p>
        <p>Tout cela pour dire que finalement l'important n'est pas la cause que vous défendez, car il s'agit simplement d'une opinion (qui peut être partagée par d'autres), mais rarement d'une universalité. Ce qui est important c'est la façon dont vous la défendez. </p>
        <p>Au final ce que j'admire, c'est la personne animée par ses convictions, son authenticité,  ses talents (d'écriture, d'interprétation, d'esthétisme, de peinture,...). Son point de vue peut être critiqué, non partagé, mais je reste toujours admirative des gens qui exposent leur opinion ou vision avec intelligence, savoir, finesse, esthétisme et talent. Dans tous les cas la forme peut être saluée, pour le travail, pour la réflexion qu'elle a suscité. </p>
        <p>Donc c'est cela que j'admire : lorsque la forme est juste, à la croisée de la beauté, du sens, de l'authenticité et du talent.</p>",
        1 // Id/index de la catégorie
    ),
    3 => new Article(
        "Partir en voyage au fond de son jardin",
        "<p>Tout le monde n'a pas de jardin, mais on peut tous partir en voyage au bout de notre rue, explorer notre quartier, se perdre dans un parc, déambuler dans une forêt. L'aventure et l'émerveillement sont à portée de main, à portée de tous, autour de nous, gratuitement. Les publicités nous disent que pour les vacances, nous devons désirer la plage de sable fin et les palmiers, qui comme par hasard sont loin, très loin et donc chers, très chers. </p>
        <p>Il fut un temps il était facile de voyager, il n'y a même pas 7 ans, on pouvait faire un aller-retour Paris-Ljubljana pour 50 euros. Aujourd'hui ce même billet coûte entre 250 et 300 euros.  Légère augmentation ... Il y a quelques années à peine, lorsqu'on voyageait on avait un plateau repas, une place pour notre valise, et même un verre de vin si on le souhaitait. Aujourd'hui pour avoir tout ce confort, il faut payer amplement plus cher, car sinon pour le même prix, que dis-je, pour le triple du prix, on doit bourrer notre sac à main dans notre sac à dos, s'acheter un sandwich dégueulasse à 10 euros à l'aéroport, s'entasser dans des bus sur le tarmac, accuser des retards voire des suppressions. Il arrive même parfois que la compagnie envoie un mail quelques jours avant pour signaler un changement d'horaire de départ, face auquel nous avons le choix entre annuler notre voyage, payer un autre billet dans une autre compagnie, et donc en dernière minute je vous laisse imaginer l'augmentation du budget, ou tout simplement rester pris en otage et suivre les horaires changeants au bon vouloir de la compagnie. Annulé le programme prévu, l'avion partira plus tôt. Je crois qu'avec mon salaire de jobs d'été d'étudiante et de babysitting  je voyageais dix fois mieux qu'aujourd'hui avec un salaire de travailleuse en CDI.</p>
        <p>Face à cet inconfort (je n'ai même pas parlé de la place pour les jambes dans les avions), il y a une alternative : le train. Quoi que ... à moins de partir à 10h un jeudi matin et de rentrer un mardi soir à 23h, les prix des tickets sont maintenant ceux des billets d'avion. Et là encore, vous n'êtes pas sûrs de partir : grèves de la SNCF les jours de départ en vacance, là aussi la classe moyenne sert d'otage, on n'a pas attendu daesh. </p>
        <p>Alors restons libres, ne nous offrons pas volontairement aux aléas stressants et coûteux, les vacances ne sont pas faites pour ça. </p>
        <p>Allons explorer les curiosités de notre propre ville, changeons notre regard, comme le dit Sylvain Tesson, soyons à l'affut, comme le dit James Redfield, attendons-nous aux coincidences, soyons attentifs à la beauté. Rencontrons de nouvelles personnes de l'autre côté de la ville. Sentons l'air du vent qui souffle sur notre peau, la chaleur des rayons du soleil, écoutons l'oiseau qui chante, une petite fille qui rit, trouvons de l'esthétisme partout où il y en a, même si d'autres ne le voient pas. Mettons-le en valeur, faisons un album photo de ces détails du quotidien, écrivons le récit de notre sortie chez l'épicier, racontons ce que nous avons découvert en changeant d'itinéraire. </p>
        <p>Soyons les touristes de notre district, les explorateurs de nos cités et de leurs valeurs.</p>
        <p>Certains dirons même que c'est plus écologique. Je dirais simplement que c'est plus pragmatique. Allons même jusqu'à en faire un voyage féérique.</p>
        <p>Ne changez pas de billet, changez de regard.</p>",
        1 // Id/index de la catégorie
    ),
    4 => new Article(
        "Je me suis donnée comme but d'être heureuse",
        "<p>Nous les franciliens, nous sommes comme des Bernard l'hermite. Sur notre gros rocher parisien, nous nous entassons comme des coquillages. Et lorsque nous déménageons, nous nous installons dans la coquille d'un autre, et prenons notre place. Nous ne nous déplaçons pas avec notre propre coquille, comme les gens du voyage avec leurs caravanes. Nous occupons une coquille vidée, qui a appartenu à quelqu'un d'autre, et que nous nous approprions, pour un temps, en attendant de la libérer pour le bernard l'hermite suivant. </p>
        <p>Quel étrange phénomène !</p>
        <p>Et pourtant si nous laissions à l'abandon chaque coquille sans se la réapproprier, nous aurions un cimetière de coquillages qui s'épendrait de plus en plus depuis l'épicentre. </p>
        <p>Alors d'une certaine manière, ce recyclage est écologique !</p>
        <p>Et alors lorsqu'on se glisse dans la peau d'un autre, est-ce qu'on en prend ses habitudes ? Est-ce qu'on se faufile un peu plus dans son quotidien, ses habitudes ? On répète les mêmes trajets, de la chambre à la cuisine, au salon. On passe la clef dans la même serrure, on regarde la même vue. Est-ce que la coquille finit par influencer le bernard ?</p>",
        1 // Id/index de la catégorie
    ),
    5 => new Article(
        "Les affiches de cinéma",
        "<p>\"incroyable\" \"sensationnel\" \"exceptionnel\" \"à voir absolument\". Voici ce que l'on peut lire sur les affiches de cinéma sur le quai de la gare. Ne peut-on plus avoir notre propre avis ? L'affiche seule n'a-t-elle plus suffisamment de sens ? Où est notre liberté de ressentir, d'aimer ou de ne pas aimer ? Fini la surprise, l'interrogation avant de voir le film, la curiosité de la découverte. Nous sommes obligés d'aimer, tout le monde l'a apprécié avant nous, ce serait un crime de ne pas penser comme le groupe. On part avec un à priori et non avec la page blanche des émotions. Et en fait peu importe qu'ensuite on n'aime ou on n'aime pas, on a déjà acheté le billet, la consommation est faite. Et de toutes façons on ne s'avisera pas de dire qu'on n'a pas été autant emballé que les mots ne le prédisaient, qui nous croirait ? Si la presse l'a dit, si Telerama, le Figaro ou Madame l'ont dit, quel poids a notre pensée dans tout ça ? Nous serons simplement écartés du troupeau.</p>
        <p>Mais là est le but du cinéma de grande audiance : il n'est plus de se poser des questions, faire réfléchir, prendre conscience, éveiller, faire découvrir la beauté ou un autre point de vue. Ces adjectifs sont là pour appuyer la valeur du film (qui du coup n'en n'aurait pas sans ces mots ?). Et surtout qu'est-ce qu'ils provoquent au passant qui se retrouve nez à nez avec cet écran géant lorsque les portes du RER s'ouvrent ? Sur le quai étroit, en slalommant entre les voyageurs et les panneaux publicitaires, ces mots résonnent comme une sentence. Il y a quelque chose d'exceptionnel que tu n'as pas vu, que tu as loupé, que tous les autres ont déjà apprécié. Conséquence ? Tu te sens mis à l'écart, tu ressens un manque. Vite, il faut aller le combler en achetant un billet, vite rejoindre le groupe protecteur. Cela fait appel aux pulsions les plus profondes, pas de place à la réflexion et au ressenti intime et personnel.</p>
        <p>Sauf que le manque ne peut pas être comblé dans l'immédiat. Surtout si la Wifi ne marche pas. Alors s'ensuit un sentiment étrange de malaise. Nous avons perdu de notre dominance. Nous nous sentons amenuisés. Et ce sentiment est complété par l'entassement des travailleurs et jeunes mamans avec poussettes dans un train surprisement court, avec quelques rames en moins pour éviter l'expansion et répondre à la demande de densification des villes. Avec le froid automnal les grosses vestes et manteaux s'entassent dans la chaleur d'un chauffage surdosé, les aisselles dégoulinent, les enfants pleurent et les mères aux cernes et au visage pâle renfrognent leur honte et frustration. Quel environnement merveilleux pour la confiance en soi et le sentiment de dominance ! L'air commençant à manquer, le train ralentissant sur les voies pour laisser passer un train plus rapide, certaines personnes défaillent, mais heureusement ne peuvent s'écrouler sur le sol, soutenues par le groupe. Ou plutôt par sa densité. Enfin les portes s'ouvrent, la libération. L'air frais remplit les poumons, le train déverse la populasse sur les quais. Certains ont encore la force de courir, que dis-je de se taper un sprint dans les escaliers car ils ont aperçu sur l'autre quai le train en partance pour la défence, ce train carré moche qui s'emplit de costards cravates en sueur. Au dehors l'apparence de la réussité, au dedans la dignité qui s'écoule. </p>
        <p>Il ne manquerait plus qu'un salaire sous estimé à ces efforts quotidien, malgré une année reccord  en bénéfices. Et voilà une classe moyenne travailleuse pleine d'estime d'elle-même, à même de consommer librement.</p>
        <p>Et lorsque quelques mères cinquantenaires se regroupent en petit comité de résistance heureuse dans le wagon, pleines de bonne humeur et avec l'envie de partager leur journée, on les rabroue, on les accuse de \"jacasser\", de ne pas laisser tranquilles les autres voyageurs. Le système a réussi à mettre en place l'auto-censure, même plus besoin de garde-fou, le peuple s'en charge lui-même, les têtes ne doivent pas dépasser du troupeau.</p>",
        1 // Id/index de la catégorie
    ),
    6 => new Article(
        "La culpabilité et l'avis des autres",
        "<p>Et si nous mettions la culpabilité dans une boîte, à côté de l'avis des autres ? Et si nous laissions cette boîte dans un coin, à quoi ressemblerait notre vie, notre quotidien ?</p>
        <p>Quel allègement ! Prêtez attention, ne serait-ce qu'une journée, à toutes les choses que vous feriez, si vous ne pensiez pas au qu'en dira-t-on, à ce qui est bien vu ou mal vu selon notre société, notre culture ? Bien-sûr tout en restant dans le cadre de la loi quand même ! </p>
        <p>Je pense notamment à cette tâche difficile qu'est l'éducation des enfants. Combien de mères perdues, face à un choix : quel comportement adopter ? D'un côté on crie \"éducation positive\", et de l'autre on crie \"il faut poser des limites\". D'un côté on dit \"allaitement à la demande\" et de l'autre \"n'oubliez pas de prendre soin de vous\". Ces injonctions antinomiques, à l'heure du choix et sous couvert de fatigue, rendent toute micro-décision impossible à prendre. </p>
        <p>Pourtant nous aimerions bien suivre un ordre bien pensant, ce serait tellement plus simple ! Mais comme chaque chapelle prêche ses convictions avec force, il faut une sacrée personnalité pour imposer ses opinions. Ce qui est fort c'est que ces injonctions s'impriment dans le cerveau des mères, et ce sont elles-même qui s'imposent ce cauchemar. Car personne n'est là au sein de leur foyer pour leur dire comment éduquer leurs enfants, elles sont libres, et les papas aussi ! Chaque couple peut intervenir selon ses convictions, envies, besoin, sa créativité. Quelle grande liberté ! Et finalement quelle difficulté ! </p>
        <p>Car sans chemin tracé à suivre, chaque pas est un choix, chaque phrase est une décision, et assumer tout cela n'a rien de simple. D'autant qu'on peut se tromper, tatonner, expérimenter. D'autant que l'éducation n'est pas une science exacte, qu'on ne saura que dans 10 ans les conséquences de nos préceptes d'aujourd'hui, et qu'aucune généralité ne saurait s'appliquer à l'individualité d'un être unique, nouveau, différent de tout ce qui a été créé sur cette Terre auparavant. Alors certes il y a parfois des similitudes. Mais comment savoir si cette fois-ci s'en est une ... ou pas ? </p>
        <p>Dans ce surplus d'informations, de conseils, de \"il faut\", une seule voie : l'intuition. </p>
        <p>Lorsqu'on s'écoute, même si cela va à l'encontre de la généralité, le résultat est le plus souvent sûr. Nous parlerons de l'intuition dans un autre article, sujet en soi.</p>
        <p>Et une fois le choix prix, la décision actée. Combien sommes-nous à nous encombrer de la culpabilité ? </p>
        <p>J'ai pris la décision de lire un livre au lieu de jouer avec mon fils ce matin. Et tout à coup je suis de mauvaise humeur. La partie de plaisir est finie, il va falloir que je paye maintenant. Je me mets à astiquer la cuisine, je réponds à toutes les demandes de la maisonnée. Personne ne me le demande. Simplement cette voix intérieur héritée de générations de femmes saintes qui ont su s'occuper de tout le monde en se mettant de côté, sans jamais se plaindre. Le poids est lourd à porter. La honte, le non mérite s'abattent sur moi. Je suis responsable, j'ai fait un enfant, je dois m'en occuper. M'en occuper tout le temps, à tout prix ? N'est -il pas capable, lui, de s'occuper sans mère quelques instants voire quelques heures ? </p>
        <p>Je prends cet exemple mais il y en a tant d'autres. </p>
        <p>Et si, en mettant cette culpabilité dans la boîte, nous voyions ce que cela produit dans notre quotidien ? Peut-être que finalement nous perdrions cette agressivité qui soudain surgit en nous, et pas seulement contre nous, mais aussi sur les autres ? </p>
        <p>Ce qui est aussi difficile avec cette nouvelle prise de position, c'est qu'on se rend compte que le monde peut continuer sans nous. L'autre soir je décidais de me retirer dans la chambre pour regarder une série, avant même l'heure du coucher de notre fils. Son père a très bien géré. Et le petit bonhomme n'a même pas réclamé sa maman. En découvrant cela, deux sentiments contradictoires me sont venus : j'étais soulagée, je n'avais pas eu à intervenir, j'avais eu le droit à un moment de détente sans contre-partie; et en même temps je me sentais triste, je n'avais pas manqué à mon fils, il n'avait pas eu besoin de moi. </p>
        <p>En acquérant plus d'autonomie, on en donne aussi à notre entourage et à nos enfants. Quelle belle leçon de vie ! Mais l'autonomie rime parfois avec solitude. Et  pourtant, même si parfois notre entourage n'a pas besoin de nous (ce qui nous permet de nous accorder des instants de liberté), eh bien parfois il aura besoin de nous. Et parce que nous aurons su prendre ces moments de répit, que nous aurons su nous ressourcer quand cela était possible, nous serons là, nous serons là quand ils auront besoin de nous.</p>",
        1 // Id/index de la catégorie
    ),
    7 => new Article(
        "La direction",
        "<p>Dans un précédent article je parlais de l'intuition. Mais dans quelle direction nous amène cette intuition ? </p>
        <p>A quoi répond cette intuition ? Essaye-t-elle de satisfaire nos besoins ? Et je ne parle pas seulement de nos besoins primaires, mais également de notre besoin de sens par exemple. </p>
        <p>Est-elle notre guide pour contenter nos désirs tout en subvenant à notre besoin de sécurité ? </p>
        <p>Nous permet-elle d'évoluer ?</p>",
        1 // Id/index de la catégorie
    ),
    8 => new Article(
        "Lettre aux femmes d'aujourd'hui",
        "<p>On a beau être des supers woman, ne cherchez pas à tout porter vous même. Demandez de l'aide, déléguez, faites en sorte de responsabiliser les gens autour de vous pour ne pas les porter à bout de bras et jouer le rôle de mère pour tout le monde. Focalisez-vous sur ce pour quoi vous êtes douée, et déléguez le reste. </p>
        <p>Comme m'a dit la sage femme au moment de l'accouchement, ce n'est pas parce que vous allez tenir une heure de plus sans péridurale que vous allez gagner une médaille. Dans la vie c'est pareil, ce n'est pas parce que vous allez tout endurer que vous en serez récompensée, surtout s'il existe des moyens de vous soulager. Utilisez-les sans culpabilité !</p>
        <p>Etes-vous prête à souffrir pour pouvoir dire dans un diner mondain, \"je l'ai fait\"? Et quoi ... ? Une minute après on passera à une autre conversation. Par orgueil, pour être admirée, vous seriez prête à vous essouffler alors qu'un autre chemin se présente à vous, avec moins de souffrance ? On a trop dit aux femmes \"vous enfanterez dans la douleur\", et on dirait qu'elles ont compris \"vous vivrez dans la douleur\". </p>
        <p>Que fait un homme après le travail ? Il se repose. Pourquoi les femmes n'y arrivent-elles pas si souvent ? Nous le méritons pourtant tout autant. Mais nous voyons toutes ces petites choses à faire et on ne peut s'empêcher de tout accomplir, avant de se détendre. Notre bien-être passe après tout le reste, même si personne ne nous l'impose. </p>
        <p>Jadis la femme devait être disponible pour son mari et ses enfants. Maintenant elle doit l'être dans le travail également. La liste des tâches est donc longue avant d'arriver au repos, sachant que le temps disponible pour chaque activité a été fortement réduit par la multiplicité des tâches. Et on continue de vouloir tout faire comme avant, gérer la maison pour qu'elle soit propre, avec pour seul modèle nos mères au foyer, avoir des enfants bien éduqués tout en devant les laisser plus de 10 h par jour à une nounou, être femme aimante et sexy, toujours jeune et aprêtée pour son mari, selon les codes véhiculés par les médias, ... et en plus de tout cela, nous souhaitons être ultra performantes dans notre travail, pour prouver aux hommes que nous aussi nous en sommes capables. Et biensûr il faut continuer d'être \"cool\", de sortir avec ses amies, voir des expos, connaître le dernier film au cinéma et voyager à chaque vacances scolaires. Nous cumulons avec tous ces rôles plusieurs jobs en même temps. </p>
        <p>Voilà, grâce au féminisme, nous avons acquis de nouveaux droits, mais tout en conservant une culture bien ancrée dans notre mémoire génétique qui n'a pas encore évolué aussi vite que ces changements, ce qui a pour conséquences de créer des femmes à bout de souffle, courant après le temps, pleines de culpabilités, n'étant jamais assez bonnes mères puisqu'absentes, jamais d'assez bonnes employées puisqu'il faut partir chercher les enfants à l'école, jamais d'assez bonnes amantes puisque la quantité d'énergie et de sommeil nécessaire n'est jamais au rdv, jamais d'assez bonnes amies puisqu'il n'y a qu'un samedi de libre le mois prochain pour se rencontrer,... et jamais d'assez bonnes petites filles pour avoir le temps de faire la route jusqu'au village reculé de la grand-mère.</p>",
        1 // Id/index de la catégorie
    ),
    9 => new Article(
        "L'intuition",
        "<p>Nous sommes des êtres grégaires, et pour notre sécurité nous avons appris à nous fondre dans le groupe, à suivre les directives imposées par lui. Cela est d'ailleurs souvent plus facile, et nous économise l'énergie de penser. </p>
        <p>Mais parfois on nous lâche tout à coup dans le grand bain des décisions, en nous demandant, et toi qu'est-ce que tu veux ? </p>
        <p>Sauf qu'on ne nous a jamais appris à nous écouter. </p>
        <p>Combien de lycéens perdus dans le labyrinthe de l'orientation professionnelle ? Combien de célibataires perdus dans la toile ? </p>
        <p>Nous avons pourtant été dotés d'une fabuleuse boussole intérieure, qui peut nous guider dans la bonne direction à tout moment. </p>
        <p>Certains parleront d'âme, d'autres d'esprits, de petite voix intérieure, peu importe le nom que vous lui donnez. Cette intuition est peut-être tout simplement la somme des informations que votre cerveau a glâné ici et là et enregistré de façon méthodique sans qu'il apporte ces données à votre conscience, car il y a déjà tellement d'informations à traiter qu'on ne pourrait pas tout analyser en temps et en heure. Pourtant ces messages reçus sont peut-être stockés quelque part dans l'inconscient, et notre merveilleuse machine à calculer qu'est notre cerveau arrive à ressortir la bonne information au bon moment, même à la synthétiser en une décision qui nous semble juste. Nous n'arrivons pas à l'expliquer de façon rationnelle. Parfois même la raison va contre notre intuition. et pourtant la raison n'a pas toutes les données, alors que l'intuition si. </p>
        <p>Combien de fois me suis-je dis non, cette intuition n'a pas de sens, je vais suivre ma raison, pour ensuite me rendre compte d'un élément plus tard que je n'avais pas pris en compte et qui justifiait ma première intuition. Combien de fois ne me suis-je pas dis, j'aurais dû m'écouter ! </p>
        <p>Après peu importe le fonctionnement de l'intuition, il n'y a pas besoin de décrire son mécanisme ou de la comprendre pour simplement se rendre compte par l'expérience que ça marche. Pourquoi attendre une validation scientifique pour utiliser une théorie qui marche ? Mettre des mots dessus la rendra-t-elle plus efficace ? Connaisons-nous mieux le pinguin depuis que nous l'avons appelé pinguin ? </p>
        <p>En cela j'ai vu les limites de la science, qui je pensais m'apporterait la compréhension du monde. Or je n'ai appris qu'à nommer et décrire les choses. Je connaissais tous les noms latins, je les rangeait dans des classements, mais je n'ai rien compris à l'essence de la nature et du monde qui nous entoure.</p>
        <p>L'art a quant à lui apporté des réponses, ou du moins des ressentis, des points de vues, des sentiments qui collaient plus à la réalité de notre expérimentation du monde finalement. </p>
        <p>Il crée des ponts entre les ressentis des gens, mais ce n'est qu'un amas de points de vues, plus ou moins partagés.</p>
        <p>La sociologie, la psychologie m'ont permi de comprendre la façon dont tous ces points de vue étaient créés. Ils ont mis en évidence les spectres à travers lesquels se formaient les réalités de chacun. </p>
        <p>Mais finalement comprendre ne suffit pas à vivre.</p>
        <p>La meilleure façon de comprendre le monde est de s'y plonger, d'expérimenter, d'en faire partie, de le vivre intensément au plus profond de soi, en interaction avec ce qui nous entoure. Finalement peu importe de le conceptualiser. Cela peut aider c'est sûr, mais ce n'est pas suffisant. </p>
        <p>Et suivre ses intuitions est une bonne façon de traverser cette vie, ce monde. Cela nous mène à des surprises, nous donne confiance, nous pousse à vivre des choses. </p>
        <p>C'est ainsi une posture que nous adoptons face à la vie : être attentif à ce qui nous entoure et à soi (ses sentiments, son état). Etre curieux et ouvert aux imprévus, aux beautés de ce monde. </p>
        <p>L'intuition fait la synthèse du monde scientifique (avec ses données physiques et ses lois naturelles), du monde artistique (en étant attiré par la beauté, forme de justesse, d'attirance vers ce qui nous convient), du monde psychologique et sociologique (prendre en compte ses sentiments et ceux des autres), pour enfin faire naître une idée, une envie, un élan à la croisée de tous ces chemins.</p>",
        1 // Id/index de la catégorie
    ),
    10 => new Article(
        "Ma peinture",
        "<p>Ma peinture, sous ses apparences abstraites, permet à chacun de laisser la place à l'inconnu et au non défini, ainsi à l'imagination. </p>
        <p>On peut y voir un paysage, ondulant sous le relief, avec les reflets du soleil qui irisent sur la surface de l'eau. On peut y voir des couches géologiques, de la lave parfois, des collines verdoyantes et des rivières. </p>
        <p>Il n'y a pas d'échelle, on peut être dans l'infiniment grand comme dans l'infiniment petit.</p>",
        1 // Id/index de la catégorie
    ),
    11 => new Article(
        "Se contenter de ce que l'on a",
        "<p>\"Le bonheur c'est de continuer à désirer ce que l'on possède\"</p>
        <p>Certes ne pas courir de désir en désir, de façon éternellement insatisfait, semble prometteur. Se contenter de ce que l'on a, être heureux ainsi, et voilà en une phrase nous sommes au Paradis. Mais en sommes-nous seulement capables ? </p>
        <p>Une société qui se contenterait de ce qu'elle a formerait un peuple parfait, qui ne se révolte jamais, reste gentiment à sa place, même inconfortable. </p>
        <p>Cette phrase dédouane de toute expérimentation vers autre chose. Cela déculpabilise les fainéants. </p>
        <p>Alors comme ça il faudrait se contenter des difficultés du quotidien, voire les désirer même ! Mais la culture, la civilisation  n'a-t-elle pas progressée parce que justement certains ont remis en cause cet ordre admi, et n'ont pas simplement désiré ce qu'ils avaient ? </p>
        <p>Aurions-nous fini notre évolution ? Pouvons-nous nous dire, on s'en arrête là ?</p>",
        1 // Id/index de la catégorie
    ),
    12 => new Article(
        "Sécurité et liberté",
        "<p>Dans son ouvrage parlant de la panthère des neiges, Sylvain Tesson nous parle des yacks, qui tels les hommes ont troqué leur liberté contre la sécurité. </p>
        <p>A cela je réponds : de quelle liberté parle-t-on lorsqu'il n'y a pas de sécurité ? La liberté de se faire dévorer à tout moment ? Certes la mort peut être une libération. Mais je ne suis pas sûre que l'inquiétude soit la meilleure des formes de liberté.</p>
        <p>Ce n'est qu'une fois nos besoins primordiaux satisfaits, que nous avons notre soupe comme dit justement Sylvain Tesson, notre toit quotidien, que nous pouvons laisser libre court à nos pensées, que celles-ci sont libérées de toute contrainte et que nous pouvons notamment avoir le temps de les coucher sur papier. </p>
        <p>Prenons un exemple : pendant des millénaires les femmes dépendaient de leur mari (et de son salaire) pour subvenir à leurs besoins. Aujourd'hui, maintenant qu'il est possible pour elles de travailler, de gagner leur vie, et grâce à l'Etat français d'au moins toucher le RSA, elles ont ce filet de sécurité qui leur permet d'avoir la liberté de choisir leur bonheur, en décidant de vivre auprès de leur mari ou si la situation ne leur convient pas de divorcer. Cette liberté de choix est permise grâce à la sécurité dont elle peuvent bénéficier, ici en France tout du moins. Mais ceci est une sécurité relative, et donc une liberté conditionnelle également. Ce n'est pas avec un RSA qu'une femme peut subvenir seule aux besoins d'elle-même et de ses enfants. Et donc certaines femmes n'ont pas cette liberté encore aujourd'hui. Je parle de femme mais tout ceci peut être écrit pour un homme également, les temps changent, et parfois ce sont les hommes qui sont au foyer. En cela le concept de revenu universel d'existance basé sur un chiffre convenable prenant en compte  la réalité d'aujourd'hui  donne l'espoir d'une plus grande liberté pour chacun. </p>
        <p>Il en est de même sur le plan professionnel. Il est certes possible de trouver un travail au SMIC, beaucoup de secteurs recrutent sans trouver chaussures à leur pied. Ce travail apporte une sécurité minimale, pour payer un loyer, pour assurer un minimum. Mais si l'on souhaite se réorienter, faire une formation, tenter l'expérience de l'entreprenariat, tout cela dans le but d'une plus grande satisfaction personnelle et professionnelle, afin d'exprimer ses talents, de mettre à profit ses compétences, eh bien ce temps de transition n'est possible qu'avec un filet de sécurité. Le loyer n'attend pas, le ventre non plus. Il est clair que cette transformation, ou du moins cette expérimentation, car on peut essayer sans réussir, serait facilitée avec un revenu universel d'existance. </p>
        <p>A travers ces deux exemples transparaît la question : où se situe la liberté ? Dans le minimum syndical permettant de subvenir à ses besoins primaires, et dans ce cas la liberté est simplement celle de vivre ou survivre ? Ou bien dans la recherche d'une forme de bonheur, d'un épanouissement personnel, d'une élévation de l'esprit voire de la culture ? </p>
        <p>A nous de décider, pays des droits de l'Homme et de la liberté, quelle liberté voulons-nous pour demain.</p>",
        1 // Id/index de la catégorie
    )
];

// Les catégories
$dataCategoriesList = [
    // ID => objet Category
    1 => new Category('THEME 1'),
    2 => new Category('THEME 2'),
    3 => new Category('THEME 3'),
    4 => new Category('THEME 4')
];